### ISSUE TITLE
Prevent working in full-screen apps/games?

### ISSUE THREAD

**Issue by Espionage724** [timrobertsdev/hotcorners#12]
https://github.com/taviso/hotcorner/issues/27

This tool also works from within full-screened games (Dota 2 DX11, Xonotic, Titan Quest AE DX9).

I don't know if I realistically throw my cursor to the top-left in shooters or games, but the idea of it happening during an intense-firefight on UT99 doesn't sound good :p

**Comment by timrobertsdev** [comment]
That's fair, I'll have a look and see if there's a flag that I can check to see if there's a fullscreen or windowed borderless app focused.

**Comment by timrobertsdev** [comment]
Added this functionality in the latest commit, official release coming SoonTM.
